name: Dispatch Private Pages Repo

on:
    push:
        branches: ["main"]

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Send repository dispatch
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.PRIVATE_PAGES_PAT }}
                  repository: your-username/status-pages
                  event-type: trigger-build
                  client-payload: '{"ref": "${{ github.ref }}"}'
